### ISSUE TITLE
Top level class is not logged

### ISSUE THREAD

**Issue by Upamo** [radarsh/gradle-test-logger-plugin#204] opened 2021-04-19 10:12 UTC
**Description**

The class name or display name of the top level test class is not printed if the class contains tests only in nested classes.
This is especially confusing if you use @DisplayName for all tests because then you have no information about which top level tests the nested tests belong to.

**Versions**

- Test logger version: 3.0.0
- Gradle version:  7.0
- Java version:  AdoptOpenJDK (build 11.0.9+11)

**Type of test being run**

Junit 5 tests:
```
package com.foo.bar;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

@DisplayName("Top level test class")
class NestedTests {
    @DisplayName("nested class A")
    class NestedClassA {

        @Test
        @DisplayName("test A")
        void testA() {
        }
    }

    @Nested
    @DisplayName("nested class B")
    class NestedClassB {

        @Test
        @DisplayName("test B")
        void testA() {
        }
    }
}
```

**Test logger configuration**

Default configuration.

**Screenshots**

Actual log output:
```
nested class B

  Test test B PASSED

nested class A

  Test test A PASSED
```

Expected log output:
```
Top level test class

  nested class B

    Test test B PASSED

  nested class A

    Test test A PASSED
```

**Additional information**

As workaround I added a dummy test at top level but that's not nice.

**Comment by radarsh** [comment] 2021-04-19 10:23
Potential duplicate of #141 and #146

**Closed** 2021-11-02 15:58 UTC
Labels: bug
