### ISSUE TITLE
Feature: suppress logging output for successful tests

### ISSUE THREAD

**Issue by molexx** [radarsh/gradle-test-logger-plugin#61] opened 2018-05-24 09:51 UTC
I'm not sure if this is within this project's remit, or if there's a better way to do it, but:

When a test fails I wish I'd increased app (not test) logging verbosity. But when tests are good that logging is verbose and very cluttery. Could gradle-test-logger optionally capture the running program's output (I assume slf4j is outputting to stdout) and only output it if the test fails?

**Comment by radarsh** [comment] 2018-05-24 16:48
It does capture standard out and standard err if you [enable the `showStandardStreams`](https://github.com/radarsh/gradle-test-logger-plugin#show-standard-streams) flag. I think your other requirement may be a duplicate of #38 which I am currently working on.

**Comment by molexx** [comment] 2018-05-24 21:45
Thanks. That's interesting... `showStandardStreams` wasn't working for me but that's because I habitually pass `--info` on the commandline, it seems that this plugin applies that (or something similar) itself so I shouldn't provide it.

I'm not sure if #38 is quite what I want - I still want to see successful tests listed with a helpful green 'PASSED', I just don't want to see their slf4j logging.

I think what would do it is an enhancement of `showStandardStreams` to add a value of `failedTestsOnly` (or, maybe for continuity with #38 , `showOnlyFailed`) alongside `true` and `false`.

**Comment by radarsh** [comment] 2018-08-30 14:56
I have introduced three new filter flags - `showPassedStandardStreams`, `showSkippedStandardStreams` and `showFailedStandardStreams` to handle this. These flags have a default value of `true`. So if we have the overall setting`showStandardStreams` set to `true`, everything is displayed. One can selectively hide passed / skipped / failed standard stream output by disabling the corresponding filter flags.

There are [three more filter flags](https://github.com/radarsh/gradle-test-logger-plugin#filter-test-results) that filter the full test output (standard streams and the test logger output containing PASSED, FAILED etc) that were introduced in a previous change.

**Closed** 2018-08-30 15:06 UTC
Labels: feature

**Comment by molexx** [comment] 2018-09-07 09:50
I've tested this, looks good thanks!

**Comment by radarsh** [comment] 2018-09-07 09:52
@molexx great. I'll be releasing a new version with these changes today or tomorrow at most.
