### ISSUE TITLE
Display start of the test

### ISSUE THREAD

**Issue by tchiotludo** [radarsh/gradle-test-logger-plugin#165] opened 2020-09-26 06:34 UTC
I've some flaky test that can end with infinite loop.
Running this test in CICD (github action) is quite complexe because this plugin will output only the end of the test result so we have some trouble finding with test will never end (until timeout).
Is there anyway to print a line at the start (with pending status) and clear the line at the end with the result ? 
(maybe this feature will not be compatible with parallel test)

**Comment by radarsh** [comment] 2020-10-15 13:09
Duplicate of #100

**Closed by radarsh** 2020-10-15 13:09 UTC
Labels: feature
